### ISSUE TITLE
log(Cash Flows) shows infinite bar

### ISSUE THREAD

**Issue by fdw** [andreasgerstmayr/fava-portfolio-returns#14]
Maybe (probably) I'm doing something wrong, but I see a very large bar in the "log(Cash Flows)" graph. There is no value on the y-axis, and when toggling `Logarithmic` off, the bar vanishes completely. The tooltip also shows `-0.00€`.

On this date, I moved many shares from one depot to another, so there was some movement, but without any value difference. I could imagine that taking the `log` of that `0` leads to unexpected results. Is that possible or did I make a mistake somewhere?

**Comment by andreasgerstmayr** [comment]
> I could imagine that taking the log of that 0 leads to unexpected results

That's spot on. I fixed this issue recently in the [upstream echarts PR](https://github.com/apache/echarts/pull/16547) but didn't rebuild my fork of echarts yet. I'll merge #18 once CI passes.

**Comment by andreasgerstmayr** [comment]
Should be fixed now. Let me know if it's still an issue.
