### ISSUE TITLE
Error with multi-currency groups

### ISSUE THREAD

**Issue by c-vigo** [andreasgerstmayr/fava-portfolio-returns#7]
The plugin raises an exception when a group is defined with multiple cash currencies. Following the example included, if one defines a group

> group {
&nbsp;&nbsp; currency: "USD"
&nbsp;&nbsp; name: "Portfolio"
&nbsp;&nbsp; investment: "Assets:US:*"
}

then an exception is raised:
`AssertionError: Inventory has more than one expected position: (90176.08 USD, 110.00 EUR)`
On the other hand, beangrow-returns is able to produce the expected reports without issues.

**Comment by andreasgerstmayr** [comment]
@c-vigo: can you try again with the latest changes? it should work now with multiple currencies in the same group.
